import { ClerkProvider } from "@clerk/nextjs"
import './globals.css';
import { ModalProvider } from "@/providers/modal-provider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<ClerkProvider>	
			<html lang="en">
				<body className="bg-red-50">
					<ModalProvider />
					{children}
				</body>
			</html>
		</ClerkProvider>
  )
}
